### ISSUE TITLE
Use node-sass 3.4.0

### ISSUE THREAD

**Issue by ComMouse** [arrowrowe/tam#10]
3.4.0 which uses libsass 3.3.0 has fixed a critical bug in escaping characters `\1234`, which would affect the bootstrap-sass build.

Thx.

**Comment by arrowrowe** [comment]
Thanks for reminding. Will finish this tonight.

**Comment by arrowrowe** [comment]
Fixed via e451f25ab1c39c9efb124127747e92112e71f109.
