### ISSUE TITLE
Update dependencies for Node 8.x

### ISSUE THREAD

**Issue by ComMouse** [arrowrowe/tam#15]
Old versions of dependencies like node-sass don't work under Node 8.x. Please fix the problem. Thank you.

**Comment by arrowrowe** [comment]
:scream:

**Comment by ComMouse** [comment]
Seems to be fixed with rebuild.... Sorry for this issue.

**Comment by at15** [comment]
@ComMouse 打豆豆 ... 以及 @arrowrowe gh 有警告你 dependency 的 CVE 么?

**Comment by arrowrowe** [comment]
@at15 警告过, 然后就升了下。。

**Comment by at15** [comment]
@arrowrowe 赞咩
