### ISSUE TITLE
Bundle with frameworks

### ISSUE THREAD

**Issue by at15** [arrowrowe/tam#2]
If I want to use it with Laravel, I still need to write my own blade template or do some hacky stuff to make tam work.  And I don't know if tam will have conflict with other front-end mange solutions, like `elixir`.

btw: The doc does not tell the differences between tam and other popular solutions.

**Comment by arrowrowe** [comment]
Agree.

**Comment by at15** [comment]
@arrowrowe thx, I think it's better to put the bundle in other repos, I will handle the bundle for golang web  frameworks after I tried it `Ayi`

**Comment by arrowrowe** [comment]
Maybe we should write a composer package for this some day.

**Comment by at15** [comment]
@arrowrowe we already had a blade plugin, any plan to release it?

**Comment by arrowrowe** [comment]
re @at15: we have to extract it out first......

**Comment by at15** [comment]
@arrowrowe we have to finish that project first, would you kindly start working on it (bioshock)

**Comment by arrowrowe** [comment]
![Would you kindly](https://41.media.tumblr.com/427391fc5c67e307c3d69a48f3007754/tumblr_nzzats1mGw1twawxwo1_500.jpg)

**Comment by at15** [comment]
well ... time flies /w\
