### ISSUE TITLE
Support assets.js?

### ISSUE THREAD

**Issue by at15** [arrowrowe/tam#4]
Using js won't need all the `"`, and won't get warning from editors when adding comments.

**Comment by arrowrowe** [comment]
In fact we can use `.js` suffix and comments (cause Tam simply read, strip comments, parse) but `"` is still necessary.

Support real js may be useful..... I will think about it.

**Comment by arrowrowe** [comment]
Denied, cause I cannot figure out a sample where real js is necessary.

**Comment by at15** [comment]
@arrowrowe e ... use js instead of json is one of the reasons I use gulp instead of grunt, and though you can add comment in json and strip them later, you will get many hint from ide like phpstorm, but since the config for tam is not very complex (and should not be) using js maybe overweight

**Comment by arrowrowe** [comment]
I do not want to add this just to avoid IDE hints......

(What's wrong with Gulp and Grunt?...

**Comment by at15** [comment]
@arrowrowe gulp use js and grunt use json. using js make it easier to write complex logic, though tam is a quite different type, so this may not apply to tam.

**Comment by arrowrowe** [comment]
True that js makes complex logic easier to write, but inside `assets.json` there should not be complex logic.
